#!/usr/bin/env bash

# Current script's directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Purge all docker data to start from scratch
read -p "The following operation will purge your docker system to start from scratch (can include data from other docker projects, if no references exist anymore). Do you know what you do and want to start from scratch? (Y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    $DIR/stop

    # Delete Ilias environment files
    for f in $DIR/../ilias/env*
    do
        rm $f
        echo "[*] Deleted $f"
    done

    # Delete nginx environment files
    rm $DIR/../nginx/.nginx_proxy_env
    echo "[*] Deleted nginx/.nginx_proxy_env"

    # Purge docker data
    docker system prune -f
    docker volume prune -f

    echo "[✓] Purge operation complete."
else
    echo "[✗] Purge operation stopped, nothing changed."
fi
