#!/usr/bin/env bash
# Current script's directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "Starting hosted blue print..."
# Check docker network and create, if not exists
echo "[*] Creating elearning docker network"
docker network inspect elearning >/dev/null 2>&1 || \
    docker network create --driver bridge elearning

echo "[*] Starting Nginx reverse proxy..."

docker-compose --file $DIR/../nginx/docker-compose.yml up -d

echo "[*] Waiting Nginx to launch on Port 80..."

while ! nc -z localhost 80; do   
  sleep 0.1
done

for f in $DIR/../ilias/env*
do
    echo "[*] Starting docker image with env file: $f"
    docker-compose --env-file $f --file $DIR/../ilias/docker-compose.yml up -d
done

echo "[✓] All containers in the environment started successfully."
